# Generated by Django 3.2.8 on 2021-11-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=100)),
                ('issue_description', models.TextField()),
                ('img', models.TextField()),
                ('call', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='like_comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='miss',
            field=models.TextField(null=True),
        ),
    ]
